import type { GameServer } from '../types';

let serverIdCounter = 0;
const generateId = () => `gs-${(++serverIdCounter).toString(36).padStart(8, '0')}`;

export const mockServers: GameServer[] = [
  {
    id: '1',
    serverId: generateId(),
    name: 'Survival World',
    gameType: 'MINECRAFT_VANILLA',
    status: 'RUNNING',
    maxPlayers: 10,
    region: 'us-east-1',
    cpuLimit: '500m',
    memoryLimit: '1024Mi',
    storageGb: 5,
    connectAddress: 'gamecont.io:31001',
    gamePort: 25565,
    nodePort: 30001,
    proxyPort: 31001,
    ownerId: 'user-1',
    ownerUsername: 'admin',
    createdAt: '2025-01-15T10:30:00Z',
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: '2',
    serverId: generateId(),
    name: 'Modded Mayhem',
    gameType: 'MINECRAFT_MODDED',
    status: 'SLEEPING',
    maxPlayers: 20,
    region: 'eu-west-1',
    cpuLimit: '1000m',
    memoryLimit: '2048Mi',
    storageGb: 10,
    connectAddress: null,
    gamePort: 25565,
    nodePort: 30002,
    proxyPort: 31002,
    ownerId: 'user-1',
    ownerUsername: 'admin',
    createdAt: '2025-02-20T14:00:00Z',
    lastActiveAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: '3',
    serverId: generateId(),
    name: 'Creative Builds',
    gameType: 'MINECRAFT_VANILLA',
    status: 'STOPPED',
    maxPlayers: 5,
    region: 'us-west-2',
    cpuLimit: '250m',
    memoryLimit: '512Mi',
    storageGb: 2,
    connectAddress: null,
    gamePort: 25565,
    nodePort: 30003,
    proxyPort: null,
    ownerId: 'user-1',
    ownerUsername: 'admin',
    createdAt: '2025-03-10T08:00:00Z',
    lastActiveAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '4',
    serverId: generateId(),
    name: 'PvP Arena',
    gameType: 'CUSTOM',
    status: 'RUNNING',
    maxPlayers: 50,
    region: 'ap-southeast-1',
    cpuLimit: '2000m',
    memoryLimit: '4096Mi',
    storageGb: 20,
    connectAddress: 'gamecont.io:31004',
    gamePort: 25565,
    nodePort: 30004,
    proxyPort: 31004,
    ownerId: 'user-1',
    ownerUsername: 'admin',
    createdAt: '2025-04-01T12:00:00Z',
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: '5',
    serverId: generateId(),
    name: 'MiniGames Hub',
    gameType: 'MINECRAFT_VANILLA',
    status: 'ERROR',
    maxPlayers: 16,
    region: 'eu-central-1',
    cpuLimit: '500m',
    memoryLimit: '1024Mi',
    storageGb: 3,
    connectAddress: null,
    gamePort: 25565,
    nodePort: null,
    proxyPort: null,
    ownerId: 'user-1',
    ownerUsername: 'admin',
    createdAt: '2025-05-05T16:00:00Z',
    lastActiveAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '6',
    serverId: generateId(),
    name: 'Skyblock',
    gameType: 'MINECRAFT_MODDED',
    status: 'STARTING',
    maxPlayers: 10,
    region: 'us-east-1',
    cpuLimit: '500m',
    memoryLimit: '1024Mi',
    storageGb: 4,
    connectAddress: null,
    gamePort: 25565,
    nodePort: null,
    proxyPort: null,
    ownerId: 'user-1',
    ownerUsername: 'admin',
    createdAt: '2025-06-01T20:00:00Z',
    lastActiveAt: new Date().toISOString(),
  },
];


